name: CI

on:
  - push
  - workflow_dispatch

jobs:
  build-windows-x64:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.git-ver.outputs.version }}
      arch-version: ${{ steps.version.outputs.arch-version }}
      pkg-name: ${{ steps.version.outputs.pkg-name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install pnpm
        run: corepack enable

      - name: Cache pnpm and node-modules
        uses: Icalinguaplusplus/node-pm-action@master
        with:
          node-modules: ./node_modules
          package-manager: pnpm

      - name: Install deps
        run: pnpm install

      - name: Get version tag
        id: git-ver
        run: echo "version=$(git describe --tags | sed 's/v//')" >> $env:GITHUB_OUTPUT

      - name: Write version info
        run: node .github/check-version.js
        id: version
        env:
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          GIT_VER: ${{ steps.git-ver.outputs.version }}

      - name: Build
        run: pnpm build
        working-directory: icalingua

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: exe-x64
          path: icalingua/build/*.exe
          if-no-files-found: error

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v.fs.')
        uses: softprops/action-gh-release@v1
        with:
          files: "icalingua/build/*.exe"
          generate_release_notes: true
          append_body: false

  build-macos-x64:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.git-ver.outputs.version }}
      arch-version: ${{ steps.version.outputs.arch-version }}
      pkg-name: ${{ steps.version.outputs.pkg-name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install pnpm
        run: corepack enable

      - name: Cache pnpm and node-modules
        uses: Icalinguaplusplus/node-pm-action@master
        with:
          node-modules: ./node_modules
          package-manager: pnpm

      - name: Install deps
        run: pnpm install

      - name: Get version tag
        id: git-ver
        run: echo "version=$(git describe --tags | sed "s/v//")" >> $GITHUB_OUTPUT

      - name: Write version info
        run: node .github/check-version.js
        id: version
        env:
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          GIT_VER: ${{ steps.git-ver.outputs.version }}

      - name: Build
        run: pnpm build
        working-directory: icalingua

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: dmg-x64
          path: icalingua/build/*.dmg
          if-no-files-found: error

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v.fs.')
        uses: softprops/action-gh-release@v1
        with:
          files: "icalingua/build/*.dmg"
          generate_release_notes: true
          append_body: false
